version: "3.7"

networks:
  reverse-proxy:
    external: true

services:
  main:
    image: ghcr.io/mealie-recipes/mealie:v2.5.0
    volumes:
      - /mnt/user/docker/volumes/mealie/data:/app/data
    ports:
      - 9925:9000
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 99
      PGID: 100
      TZ: America/Chicago
      BASE_URL: https://mealie.actuary.dev
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: 192.168.2.2
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: mealie
      #OIDC settings
      OIDC_AUTH_ENABLED: "true"
      OIDC_SIGNUP_ENABLED: "true"
      OIDC_CONFIGURATION_URL: "https://authentik.actuary.dev/application/o/mealie/.well-known/openid-configuration"
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_AUTO_REDIRECT: "true"
      OIDC_REMEMBER_ME: "true"
      OIDC_USER_GROUP: "friends"
      OIDC_ADMIN_GROUP: "authentik Admins"
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      #OPENAI Settings
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - reverse-proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mealie.rule=Host(`mealie.actuary.dev`)"
        - "traefik.http.routers.mealie.entrypoints=websecure"
        - "traefik.http.routers.mealie.service=mealie"
        - "traefik.http.routers.mealie.tls.certresolver=myresolver"
        - "traefik.http.services.mealie.loadbalancer.server.port=9000"
        - "traefik.http.routers.mealie.middlewares=authentik@file"
        #homepage labels
               #Widget
        - "homepage.widget.type=mealie"
        - "homepage.widget.url=http://192.168.2.3:9925"
        - "homepage.widget.key=${MEALIE_HOMEPAGE_API_TOKEN}"
        - "homepage.widget.version=2"
